language: python

git:
  depth: 999999

cache: pip

install: 
  - pip install -U pip wheel
  - pip install urubu

script: make

deploy:
  skip_cleanup: true
  provider: script
  script: ./travis-deploy-ghpages.sh
  on:
    branch: master
